version: '3'
services:
  app:
    container_name: app
    build: .
    depends_on:
      - redis
    ports:
      - "5000:80"
    volumes:
      - "./static:/app/app/static/"

  redis:
    container_name: redis
    image: redis:5
